test

diff --git a/.github/workflows/firmware_build_test.yml b/.github/workflows/firmware_build_test.yml
--- a/.github/workflows/firmware_build_test.yml
+++ b/.github/workflows/firmware_build_test.yml
@@ -3,7 +3,7 @@ name: Firmware Build and SITL Tests
 on:
   push:
     branches:
-      - main
+      - master
   pull_request:
     branches:
       - '*'
@@ -21,30 +21,30 @@ jobs:
       image: px4io/px4-dev-simulation-focal:2021-05-31
       options: --privileged --ulimit core=-1 --security-opt seccomp=unconfined
     steps:
-    - name: Checkout Firmware main
+    - name: Checkout Firmware master
       uses: actions/checkout@v2.3.1
       with:
         repository: PX4/Firmware
-        ref: main
+        ref: master
         path: Firmware
         fetch-depth: 0
         submodules: recurvise
     - name: Checkout matching branch on PX4/Firmware if possible
       run: |
-        git checkout ${{github.head_ref}} || echo "Firmware branch: ${{github.head_ref}} not found, using main instead"
+        git checkout ${{github.head_ref}} || echo "Firmware branch: ${{github.head_ref}} not found, using master instead"
         git submodule update --init --recursive
       working-directory: Firmware
     - name: Configure Firmware to include current sitl_gazebo version
-      working-directory: Firmware/Tools/simulation/gazebo-classic/sitl_gazebo-classic
+      working-directory: Firmware/Tools/sitl_gazebo
       run: |
         git fetch origin pull/${{github.event.pull_request.number}}/head:${{github.head_ref}} || echo "Couldn't find the feature branch of the pull request, using default branch"
         git checkout ${{github.head_ref}}
     - name: Download MAVSDK
       working-directory: Firmware
-      run: wget "https://github.com/mavlink/MAVSDK/releases/download/v$(cat test/mavsdk_tests/MAVSDK_VERSION)/libmavsdk-dev_$(cat test/mavsdk_tests/MAVSDK_VERSION)_ubuntu20.04_amd64.deb"
+      run: wget "https://github.com/mavlink/MAVSDK/releases/download/v$(cat test/mavsdk_tests/MAVSDK_VERSION)/mavsdk_$(cat test/mavsdk_tests/MAVSDK_VERSION)_ubuntu20.04_amd64.deb"
     - name: Install MAVSDK
       working-directory: Firmware
-      run: dpkg -i "libmavsdk-dev_$(cat test/mavsdk_tests/MAVSDK_VERSION)_ubuntu20.04_amd64.deb"
+      run: dpkg -i "mavsdk_$(cat test/mavsdk_tests/MAVSDK_VERSION)_ubuntu20.04_amd64.deb"
     - name: Prepare ccache timestamp
       id: ccache_cache_timestamp
       shell: cmake -P {0}
@@ -71,7 +71,7 @@ jobs:
       env:
         DONT_RUN: 1
         GIT_SUBMODULES_ARE_EVIL: 1
-      run: make px4_sitl_default gazebo_iris
+      run: make px4_sitl_default gazebo
     - name: ccache post-run px4/firmware
       run: ccache -s
     - name: Build MAVSDK tests
@@ -79,7 +79,7 @@ jobs:
       env:
         DONT_RUN: 1
         GIT_SUBMODULES_ARE_EVIL: 1
-      run: make px4_sitl_default gazebo_iris mavsdk_tests
+      run: make px4_sitl_default gazebo mavsdk_tests
     - name: ccache post-run mavsdk_tests
       run: ccache -s
     - name: Run SITL tests
